### ISSUE TITLE
node-agent got "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by nashtsai** [coroot/coroot#403]
node-agent is crashing, check attached stack error.

coroot node-agent version: 1.22.2
OS: Debian (5.4.210-amd64)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bbfd5c]

goroutine 242 [running]:
github.com/coroot/coroot-node-agent/containers.(*Process).Close(0xc001d06380)
	/tmp/src/containers/process.go:105 +0x3c
github.com/coroot/coroot-node-agent/containers.(*Container).onProcessExit(0xc000a68780, 0x20df650?, 0x0)
	/tmp/src/containers/container.go:434 +0x96
github.com/coroot/coroot-node-agent/containers.(*Registry).handleEvents(0xc000b11ef0, 0xc0008eb680)
	/tmp/src/containers/registry.go:234 +0x3fc
created by github.com/coroot/coroot-node-agent/containers.NewRegistry in goroutine 1
	/tmp/src/containers/registry.go:124 +0x685
```

**Comment by apetruhin** [comment]
@nashtsai
I don't see how this [line](https://github.com/coroot/coroot-node-agent/blob/v1.22.2/containers/process.go#L105) could cause the `panic`, as `p` is always non-nil here. Are you using our build of node-agent? It looks like a custom build that is panicking elsewhere.
