### ISSUE TITLE
"Index out of range" problem

### ISSUE THREAD

**Issue by gdevelek** [coroot/coroot#59]
In our 0.17.6 installation on Kubernetes v1.24 we occasionally run into this issue in the Coroot pod logs:

[coroot.docx](https://github.com/coroot/coroot/files/11790142/coroot.docx)

This brings down the entire app. 

After today's incident we removed and redeployed the Helm chart, but what is the root cause of this?

**Comment by def** [comment]
It looks strange... Usually, in such cases, the full stack trace of the application is written to the log.
If you see it again, please copy the entire log.

**Comment by dtemir** [comment]
Hi @def! Facing a similar issue. Here's what I can see in standard out

```bash
I0706 20:03:51.641696       1 db.go:42] using sqlite database
I0706 20:03:51.788698       1 cache.go:131] cache loaded from disk in 146.310516ms
I0706 20:03:51.788857       1 compaction.go:81] compaction worker started
I0706 20:03:51.891763       1 main.go:140] listening on :8080
I0706 20:03:52.789837       1 updater.go:60] worker iteration for hgc7bthb
I0706 20:03:55.167308       1 constructor.go:113] got 26 nodes, 329 services, 466 applications
panic: runtime error: index out of range [1] with length 1

goroutine 40 [running]:
github.com/coroot/coroot/constructor.getInstanceAndContainer(0xc00021f500, 0x0, 0xfad3bc?, {0x0?, 0x0?})
	/tmp/src/constructor/containers.go:26 +0x87c
github.com/coroot/coroot/constructor.loadContainers(0xc00021f500, 0xbd5ae5?, 0xc00021f500?, 0x2d?)
	/tmp/src/constructor/containers.go:63 +0x1b9a
github.com/coroot/coroot/constructor.(*Constructor).LoadWorld.func7()
	/tmp/src/constructor/constructor.go:105 +0x2c
github.com/coroot/coroot/constructor.(*Profile).stage(0xc00144cbe0?, {0xfafb32?, 0xc0002aa6c0?}, 0xc000580000?)
	/tmp/src/constructor/constructor.go:59 +0x132
github.com/coroot/coroot/constructor.(*Constructor).LoadWorld(0xc00aad4810, {0x1106de8, 0xc00a54dc20}, 0x649ed3ec, 0x649ee184, 0x78, 0x0)
	/tmp/src/constructor/constructor.go:105 +0x5f0
github.com/coroot/coroot/cache.(*recordingRulesProcessor).QueryRange(0xc000274040, {0x1106de8, 0xc00a54dc20}, {0xc0002d6c00, 0x25}, 0x8?, 0x649ee184, 0x20?)
	/tmp/src/cache/updater.go:284 +0x299
github.com/coroot/coroot/cache.(*Cache).download(0xe92ea0?, 0x64a71e28, {0x1102a58, 0xc000274040}, 0xc0001bc180, 0xc000042c00)
	/tmp/src/cache/updater.go:159 +0x1c2
github.com/coroot/coroot/cache.(*Cache).processRecordingRules(0xc0002b9a00, 0xc0005e6270?, 0xc0001bc180, 0x23?)
	/tmp/src/cache/updater.go:264 +0x29c
github.com/coroot/coroot/cache.(*Cache).updaterWorker(0xc0002b9a00, 0xc00071a000?, {0xc0005d42f0, 0x8})
	/tmp/src/cache/updater.go:143 +0x90
created by github.com/coroot/coroot/cache.(*Cache).updater
	/tmp/src/cache/updater.go:45 +0x34a
```

Running it in K8S and not sure if there is a straightforward way of attaching to the pod because it keeps crashing (the container starts, app breaks, pod gets in CrashLoopBackOff.

Do you have any advice?

**Comment by def** [comment]
@dtemir, it seems like you're using an outdated version according to the stack trace. Could you please update Coroot to the latest version? If the issue continues to persist even after updating, please provide us with a fresh stack trace. We'll be happy to fix this.

**Comment by apetruhin** [comment]
@gdevelek, We've fixed the `panic`. Please upgrade Coroot to the latest version (0.17.11).
