### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by rlex** [coroot/coroot#7]
Hello!
Got this error, appears randomly. Does not crash pod with coroot, but stops responding in UI 

```
2022/10/18 00:32:49 http: panic serving 10.251.3.145:50394: runtime error: integer divide by zero
goroutine 60260 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0xaefee0, 0x1253250})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/coroot/coroot/auditor.(*appAuditor).logs(0xc001afebb8)
	/tmp/src/auditor/logs.go:92 +0x86a
github.com/coroot/coroot/auditor.Audit(0xc0124584d0)
	/tmp/src/auditor/auditor.go:32 +0x159
github.com/coroot/coroot/api/views/overview.Render(0xc0124584d0)
```

Another one: 
```
2022/10/18 00:35:14 http: panic serving 10.251.6.173:57792: runtime error: integer divide by zero
goroutine 62487 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0xaefee0, 0x1253250})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/coroot/coroot/auditor.(*appAuditor).logs(0xc01cbd6bb8)
	/tmp/src/auditor/logs.go:92 +0x86a
github.com/coroot/coroot/auditor.Audit(0xc01459a000)
	/tmp/src/auditor/auditor.go:32 +0x159
github.com/coroot/coroot/api/views/overview.Render(0xc01459a000)
	/tmp/src/api/views/overview/overview.go:41 +0x9d
github.com/coroot/coroot/api/views.Overview(...)
	/tmp/src/api/views/views.go:20
```

**Comment by apetruhin** [comment]
Hi @rlex! Thank you for the report. Please upgrade Coroot to 0.5.4
